CREATE SCHEMA IF NOT EXISTS accounts;

CREATE TABLE IF NOT EXISTS accounts.traders (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id VARCHAR(255) NOT NULL UNIQUE,
    username   VARCHAR(255) NOT NULL UNIQUE,
    api_key    VARCHAR(255) UNIQUE,
    buying_power  DOUBLE PRECISION DEFAULT 0,
    margin_limit  DOUBLE PRECISION DEFAULT 0
);

INSERT INTO accounts.traders (account_id, username, api_key, buying_power, margin_limit)
VALUES ('test-account-001', 'testuser', 'test-api-key-001', 100000.0, 50000.0);
